### ISSUE TITLE
nuheat errors

### ISSUE THREAD

**Issue by sjlu** [senorshaun/homebridge-nuheat#9] opened 2023-04-14 23:47 UTC
Got my Thermostat ID and everything, but seems that I'm running into an error all the time - any suggestions?

```
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: Successfully connected to the NuHeat API.
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: Trying again.
[15/04/2023, 00:45:37] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[15/04/2023, 00:45:37] [NuHeat] NuHeatAPI: Unable to make API call. Acquiring a new access token.
[15/04/2023, 00:45:37] [NuHeat] Error getting data from NuHeatAPI
[15/04/2023, 00:45:39] [NuHeat] NuHeatAPI: Successfully connected to the NuHeat API.
[2023-04-14T23:45:40.022Z] Information: WebSocket connected to wss://api.mynuheat.com/notificationsHost?token=xxx
[15/04/2023, 00:45:40] [NuHeat] Notification listener connection started!
[15/04/2023, 00:45:40] [NuHeat] Subscribed for notifications
```

**Comment by senorshaun** [comment] 2023-04-15 00:27
Does it work after that?On Apr 14, 2023, at 6:47 PM, Steven Lu ***@***.***> wrote:﻿
Got my Thermostat ID and everything, but seems that I'm running into an error all the time - any suggestions?
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: Successfully connected to the NuHeat API.
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[15/04/2023, 00:45:36] [NuHeat] NuHeatAPI: Trying again.
[15/04/2023, 00:45:37] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[15/04/2023, 00:45:37] [NuHeat] NuHeatAPI: Unable to make API call. Acquiring a new access token.
[15/04/2023, 00:45:37] [NuHeat] Error getting data from NuHeatAPI
[15/04/2023, 00:45:39] [NuHeat] NuHeatAPI: Successfully connected to the NuHeat API.
[2023-04-14T23:45:40.022Z] Information: WebSocket connected to wss://api.mynuheat.com/notificationsHost?token=xxx
[15/04/2023, 00:45:40] [NuHeat] Notification listener connection started!
[15/04/2023, 00:45:40] [NuHeat] Subscribed for notifications

**Comment by sjlu** [comment] 2023-04-15 00:34
It doesn’t, repeats the error and can’t retrieve the thermostat. Same happens when I try triggering Away mode.

**Comment by senorshaun** [comment] 2023-04-17 21:50
Have you restarted homebridge (or the child bridge)?

**Comment by sjlu** [comment] 2023-04-21 14:55
Yeah, I walked through the OAuth process as listed, and when running https://api.mynuheat.com/api/v1/Thermostat/<id>, I get the following error:

500
```
{
    "messages": [
        "Failed to retrieve thermostat."
    ]
}
```

I know this isn't related to the code but not sure if you have a PoC at nuheat that could help.

**Comment by senorshaun** [comment] 2023-05-12 16:07
duplicate of #10. closing this for now. please update to 1.1.4 to keep homebridge from crashing.

**Closed as completed by senorshaun** 2023-05-12 16:07 UTC
